---

# Tasks about config

- name: Include groovy configuration
  include: "{{ role_path }}/tasks/manage_main_config.yml"

- name : Get Jenkins war version
  command  : "java -jar {{ jenkins_etc_war_location }} --version"
  register : jenkins_main_cfg_version
  changed_when : False

- name : Get plugins informations
  register : jenkins_list_plugins_updated
  uri :
    url : "{{ jenkins_base_url }}/{{ jenkins_api_plugins_list }}"
    return_content : True

- name : Generate misc configuration files
  become : True
  become_user : "{{ jenkins_etc_user }}"
  register : jenkins_misc_configuration_generate
  template :
    src   : "{{ role_path ~ '/templates/configuration/misc'
      ~ '/' ~ item.template | trim }}"
    dest  : "{{ item.dest | trim }}"
    owner : "{{ jenkins_configuration_files_owner }}"
    group : "{{ jenkins_configuration_files_group }}"
    mode  : "{{ jenkins_configuration_files_mode }}"
  with_items : jenkins_misc_templates
  when : item.name in jenkins_misc_cfg

- name : Generate plugin configuration files
  become : True
  become_user : "{{ jenkins_etc_user }}"
  register : jenkins_plugin_configuration_generate
  template :
    src   : "{{ role_path ~ '/templates/configuration/' ~ item.name
      ~ '/' ~ item.template | trim }}"
    dest  : "{{ jenkins_etc_home_location ~ '/' ~ item.template
      | regex_replace('.j2$', '') | trim }}"
    owner : "{{ jenkins_configuration_files_owner }}"
    group : "{{ jenkins_configuration_files_group }}"
    mode  : "{{ jenkins_configuration_files_mode }}"
  with_items : jenkins_plugin_templates
  vars:
    jenkins_plugin: >
      {{
        ((jenkins_list_plugins_updated.content | from_json).plugins
        | selectattr('shortName', 'equalto', item.name) | first)
      }}
  when : >
    "item.name in (
    (jenkins_list_plugins_updated.content | from_json).plugins
    | map(attribute='shortName'))"

- name : Restart jenkins and waiting if new changes
  include : "{{ role_path }}/handlers/restart_and_waiting_jenkins.yml"
  when : >
    jenkins_main_configuration_generate.changed
    or jenkins_plugin_configuration_generate.changed
    or jenkins_misc_configuration_generate.changed

