---

# Tasks file for jenkins

- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- include: install_debian.yml
  tags:
    - install
    - jenkins
  when: ansible_os_family == "Debian"

- name : Restart jenkins if new version installed
  include : "{{ role_path }}/handlers/restart_jenkins.yml"
  when : jenkins_task_package_install.changed

- name : Waiting the application is available
  include : "{{ role_path }}/handlers/waiting_jenkins.yml"

- include: configure.yml
  tags:
    - configure
    - jenkins

- include: manage_cli.yml
  tags:
    - jenkins
    - install

- include: plugins.yml
  tags:
    - jenkins
    - install

