---

# These tasks manage credentials

- name: Remove all domain credentials
  become : True
  become_user : "{{ jenkins_etc_user }}"
  remove_jenkins_credentials:
    credentials_domain: "{{ item }}"
  with_items: "{{ jenkins_credentials_domains_to_empty }}"

- name: Manage credentials
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_credentials:
    credentials_type: "{{ item.credentials_type }}"
    credentials_domain: "{{ item.credentials_domain }}"
    scope: "{{ item.scope }}"
    id: "{{ item.id }}"
    username: "{{ item.username }}"
    private_key_source_type: "{{ item.private_key_source_type }}"
    private_key_source_data: "{{ item.private_key_source_data }}"
    private_key_passphrase: "{{ item.private_key_passphrase }}"
    description: "{{ item.description }}"
    state: "{{ item.state }}"
  register: jenkins_change_credentials
  with_items: "{{ jenkins_credentials }}"

