---

# These tasks manage credentials

- name : Create credentials (/!\ This reset old credentials)
  uri :
    url : "{{ jenkins_base_url }}/credentials/configSubmit"
    method: POST
    body: "json={{ jenkins_credentials | to_json }}"
    HEADER_Content-Type : "application/x-www-form-urlencoded"
    status_code: "200,302"
 
