---

# Tasks about Jenkins main configuration management

- name: Manage main configuration with new settings
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_main_configuration:
    mode: "{{ jenkins_config_mode }}"
    number_of_executors: "{{ jenkins_config_num_executors }}"
    project_naming_strategy:
      pattern: "{{ jenkins_config_project_naming_strategy.pattern }}"
      description: "{{ jenkins_config_project_naming_strategy.description }}"
      force: "{{ jenkins_config_project_naming_strategy.force }}"
    quiet_period: "{{ jenkins_config_quiet_period }}"
    slave_agent_port: "{{ jenkins_config_slave_agent_port }}"
  register: jenkins_change_main_configuration

- debug:
    var: jenkins_change_main_configuration

