---

# Tasks about Jenkins plugins configuration management

- name: Manage git plugin configuration with new settings
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_plugin_git:
    create_accounts: "{{ jenkins_plugin_git_create_account_based_on_email }}"
    email: "{{ jenkins_plugin_git_global_email }}"
    full_name: "{{ jenkins_plugin_git_global_full_name }}"
  register: jenkins_change_plugin_git

- name: Manage mailer plugin configuration with new settings
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_plugin_mailer:
    charset: "{{ jenkins_plugin_mailer_charset }}"
    default_suffix: "{{ jenkins_plugin_mailer_default_suffix }}"
    reply_to: "{{ jenkins_plugin_mailer_reply_to }}"
    smtp_host: "{{ jenkins_plugin_mailer_smtp_host }}"
    smtp_password: "{{ jenkins_plugin_mailer_smtp_password }}"
    smtp_port: "{{ jenkins_plugin_mailer_smtp_port }}"
    smtp_user: "{{ jenkins_plugin_mailer_smtp_user }}"
    use_ssl: "{{ jenkins_plugin_mailer_use_ssl }}"
  register: jenkins_change_plugin_mailer

- name: Remove github plugin servers configuration
  become: True
  become_user: "{{ jenkins_etc_user }}"
  remove_jenkins_github_servers:
    do_task: True
  when: jenkins_plugins_github_remove_servers

- name: Manage github plugin configuration with new settings
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_plugin_github:
    manage_hooks: "{{ item.manage_hooks }}"
    credentials_id: "{{ item.credentials_id }}"
    custom_url: "{{ item.custom_url }}"
    client_cache_size: "{{ item.client_cache_size }}"
  register: jenkins_change_plugin_github
  with_items: "{{ jenkins_plugins_github_servers }}"

