---

# Tasks used to manange Jenkins CLI

- name : Ensure jenkins running
  become  : True
  service :
    name  : "{{ jenkins_service_name }}"
    state : started

- name : Wait untils Jenkins web API is available
  command  : curl --head --silent {{ jenkins_base_url }}/
  register : jenkins_check_available
  until    : jenkins_check_available.stdout.find("200 OK") != -1
  retries  : "{{ jenkins_waiting_available_retries }}"
  delay    : "{{ jenkins_waiting_available_delay }}"
  changed_when : False

- name : Install Jenkins CLI
  become : True
  become_user : "{{ jenkins_config_user }}"
  get_url :
    url   : "{{ jenkins_cli_download_url }}"
    dest  : "{{ jenkins_cli_destination }}"
    force : True

