---

# Tasks about Jenkins main configuration management

- name: Manage main configuration with new settings
  become : True
  become_user : "{{ jenkins_etc_user }}"
  manage_jenkins_main_configuration:
    number_of_executors: "{{ jenkins_main_cfg_num_executors }}"
  register: jenkins_change_main_configuration

