---

# Tasks about Jenkins plugins

- name: Get plugins status
  become: True
  become_user: "{{ jenkins_etc_user }}"
  get_jenkins_plugins:
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
  register: jenkins_plugins_status
  changed_when: False

- name: Manage plugin installation
  include: "{{ role_path }}/tasks/manage_plugin_installation.yml"
  with_items: "{{ jenkins_plugins }}"

- name: Get plugins should be upgraded
  become: True
  become_user: "{{ jenkins_etc_user }}"
  get_jenkins_plugins:
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
  register: jenkins_list_plugins_for_upgrade
  changed_when: False

- name: Manage plugin upgrade
  include: "{{ role_path }}/tasks/manage_plugin_upgrade.yml"
  with_items : "{{ jenkins_list_plugins_for_upgrade.has_update }}"

