---

# Tasks about Jenkins plugins

- name : Get installed plugins
  become      : True
  become_user : "{{ jenkins_config_user }}"
  register    : jenkins_list_plugins
  shell : >
    java
    -jar {{ jenkins_cli }}
    -s {{ jenkins_base_url }}
    list-plugins
    | awk '{ print $1 }'
  changed_when : False

- name : Install required plugins
  become      : True
  become_user : "{{ jenkins_config_user }}"
  register    : jenkins_task_install_plugins
  shell : >
    java
    -jar {{ jenkins_cli }}
    -s {{ jenkins_base_url }}
    install-plugin {{ item }}
  with_items :
    - "{{
        jenkins_plugins
        | difference(jenkins_list_plugins.stdout_lines)
      }}"

- name : Waiting jenkins restarted
  include : "{{ role_path }}/handlers/restart_and_waiting_jenkins.yml"
  when: jenkins_task_install_plugins.changed

- name : Get plugins should be upgraded
  become      : True
  become_user : "{{ jenkins_config_user }}"
  register    : jenkins_list_plugins_with_upgrade
  shell : >
    java
    -jar {{ jenkins_cli }}
    -s {{ jenkins_base_url }}
    list-plugins
    | grep ')$'
    | awk '{ print $1 }'
  changed_when : False

- name : Install upgrade for plugins
  become      : True
  become_user : "{{ jenkins_config_user }}"
  register    : jenkins_task_upgrade_plugins
  shell : >
    java
    -jar {{ jenkins_cli }}
    -s {{ jenkins_base_url }}
    install-plugin {{ item }}
  with_items : jenkins_list_plugins_with_upgrade.stdout_lines

- name : Waiting jenkins restarted
  include : "{{ role_path }}/handlers/restart_and_waiting_jenkins.yml"
  when: jenkins_task_upgrade_plugins.changed

